//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int Matricula { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int Semestre { get; set; }
        public int Facultad { get; set; }
    
        public virtual Facultad Facultad1 { get; set; }
    }
}
