//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facultad
    {
        public Facultad()
        {
            this.Alumno = new HashSet<Alumno>();
            this.MateriaFacultad = new HashSet<MateriaFacultad>();
        }
    
        public int Id_Facultad { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int Universidad { get; set; }
        public int IdCiudad { get; set; }
    
        public virtual ICollection<Alumno> Alumno { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual Universidad Universidad1 { get; set; }
        public virtual ICollection<MateriaFacultad> MateriaFacultad { get; set; }
    }
}
